# Generated by Django 6.0.3 on 2026-03-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('year', models.IntegerField(null=True)),
                ('success', models.BooleanField()),
                ('img_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
