# Generated by Django 6.0.3 on 2026-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='MovieInfo',
            name='img_name',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
