# Generated by Django 6.0.3 on 2026-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_directorinfo_movieinfo_director_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='actorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='actors',
            field=models.ManyToManyField(related_name='movies_acted_in', to='movies.actorinfo'),
        ),
    ]
